name: instagram_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # uses-material-design: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/home.png
    - assets/icons/search.png
    - assets/icons/add.png
    - assets/icons/reel.png
    - assets/icons/user.png
